# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='create_time',
            new_name='createtime',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='create_time',
            new_name='createtime',
        ),
    ]
