# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20170212_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.CharField(default='https://qph.ec.quoracdn.net/main-qimg-016319d146ee93a464cb11870001b29c', max_length=250),
        ),
    ]
