# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20170222_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.FileField(null=True, upload_to='cover)image'),
        ),
    ]
