# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='video',
            field=models.ForeignKey(choices=[('like', 'like'), ('dislike', 'dislike'), ('normal', 'normal')], on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='firstapp.Article'),
        ),
    ]
