# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_auto_20170312_0901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='video',
            new_name='choice',
        ),
    ]
