# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 11:27
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_auto_20170312_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='editor_choice',
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容'),
        ),
    ]
